### ISSUE TITLE
Use a higher priority on KickedFromServerEvent

### ISSUE THREAD

**Issue by kyngs** [4drian3d/KickRedirect#30]
Currently, the plugin uses the `EARLY` priority level. This can cause conflicts with utility plugins that implement a similar feature but intentionally use `EARLY` so they can be overridden. Considering that this plugin has no other use than redirecting players after kick, it would be IMO better to use `NORMAL` or even `LATE`.

**Comment by 4drian3d** [comment]
I started using the `PostOrder.EARLY` to implement the debug mode to check for any existing conflict with another plugin, this way, the main KickRedirect listener would run in the PostOrder `Early` and the debug listener would run in the PostOrder `Last`, so by simply activating the debug mode, the user would be able to identify that there is an external plugin modifying the result given by KickRedirect.
Although since I implemented this feature, I have never received any incompatibility report, according to what you mention it may cause conflict with some other plugin that maybe I don't know, could you give me the name of that plugin?

**Comment by 4drian3d** [comment]
Ok, I just saw the compatibility problem with LibreLogin, I will try to make the PostOrder of the main listener configurable
